# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  redis_service:
    image: 'redis'
    ports:
      - "6379:6379"
    networks:
      - backendnet

  redisdemoapplication:
    image: redisdemoapplication
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
      - redis_service 
    networks:
      - backendnet
  
networks:
  backendnet:
    driver: bridge
  
